export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCHING_COMICS = 'FETCHING_COMICS';
export const FETCHING_COMICS_SUCCESS = 'FETCHING_COMICS_SUCCESS';
export const FETCHING_COMICS_FAILURE = 'FETCHING_COMICS_FAILURE';
